### ISSUE TITLE
Driver Issue

### ISSUE THREAD

**Issue by nerdwa** [abzman/chatpad#1]
Using your repaired driver, whenever I verify code I get a flag on line 39 in the chatpad.cpp. It says "Byte does not name type; did you mean 'system'?". How would I proceed from here?

**Comment by abzman** [comment]
try substituting all declarations of the variable type 'byte' with uint8_t

it looks like that is on lines 33, 34, 35, 36, 39, 40, 91, 92, 93, 96, 292

**Comment by nerdwa** [comment]
Thanks for the response. I know revisiting old projects can be tiresome. 
Anyways, I tried your suggestion and I'm still getting the same error.

**Comment by abzman** [comment]
ok, what is your environment like? I just tried it and with a folder under Documents/Arduino/libraries/chatpad (I'm using windows here) that contains Chatpad.cpp and Chatpad.h I find my original chatpad.ino compiles just fine under Arduino 2.3.2 when the board is set to arduino micro

**Comment by nerdwa** [comment]
Okay... I have no idea what I just did but it works now. Thank you very very much for helping!
